<a href="https://colab.research.google.com/github/JencyCS/DataScience/blob/main/3b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sheth L.U.J and Sir M.V. college**

# Jency Nadar T095

Encoding Nominal Categorical Feature

One-hot encode the feature using scikit-learn's LabelBinarizer

In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelBinarizer

df = pd.read_csv("Finance_data.csv", header=None, engine="python")

# column 0 contains the items
feature = df[0].values

# LabelBinarizer needs 1D input
one_hot = LabelBinarizer()
encoded = one_hot.fit_transform(feature)

print(encoded[:10])
print(one_hot.classes_)


[[0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]]
['Female' 'Male' 'gender']


In [14]:
# Reverse one-hot encoding
decoded = one_hot.inverse_transform(encoded)
print("\nDecoded (Reverse One-Hot):\n", decoded)


Decoded (Reverse One-Hot):
 ['gender' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Female'
 'Male' 'Male' 'Male' 'Female' 'Male' 'Female' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Male' 'Male' 'Male' 'Female' 'Male' 'Male' 'Female'
 'Female' 'Male' 'Male' 'Male' 'Female' 'Male' 'Female' 'Male' 'Male'
 'Male' 'Male' 'Male' 'Male' 'Male' 'Male']


In [19]:
# One hot encode with pandas
pd.get_dummies(df.iloc[:, 10])


No  Stock_Marktet    Yes
0   False           True  False
1   False          False   True
2    True          False  False
3   False          False   True
4   False          False   True
5    True          False  False
6    True          False  False
7   False          False   True
8   False          False   True
9   False          False   True
10  False          False   True
11  False          False   True
12  False          False   True
13   True          False  False
14  False          False   True
15  False          False   True
16  False          False   True
17  False          False   True
18  False          False   True
19  False          False   True
20  False          False   True
21  False          False   True
22  False          False   True
23  False          False   True
24  False          False   True
25  False          False   True
26  False          False   True
27  False          False   True
28  False          False   True
29  False          False   True
30  False          False   True
31   True          False  False
32  False          False   True
33  False          False   True
34  False          False   True
35  False          False   True
36  False          False   True
37  False          False   True
38  False          False   True
39  False          False   True
40  False          False   True

In [24]:
import pandas as pd

df = pd.read_csv("Finance_data.csv", header=None, sep="\t", engine="python")
print(df.head(10))


                                                   0
0  gender,age,Investment_Avenues,Mutual_Funds,Equ...
1  Female,34,Yes,1,2,5,3,7,6,4,Yes,Returns,Capita...
2  Female,23,Yes,4,3,2,1,5,6,7,No,Locking Period,...
3  Male,30,Yes,3,6,4,2,5,1,7,Yes,Returns,Capital ...
4  Male,22,Yes,2,1,3,7,6,4,5,Yes,Returns,Income,W...
5  Female,24,No,2,1,3,6,4,5,7,No,Returns,Income,W...
6  Female,24,No,7,5,4,6,3,1,2,No,Risk,Capital App...
7  Female,27,Yes,3,6,4,2,5,1,7,Yes,Returns,Capita...
8  Male,21,Yes,2,3,7,4,6,1,5,Yes,Risk,Capital App...
9  Male,35,Yes,2,4,7,5,3,1,6,Yes,Returns,Growth,S...


In [25]:
transactions = df.apply(lambda row: row.dropna().tolist(), axis=1)
transactions = transactions.tolist()

print(transactions[:5])

[['gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,Factor,Objective,Purpose,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source'], ['Female,34,Yes,1,2,5,3,7,6,4,Yes,Returns,Capital Appreciation,Wealth Creation,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines'], ['Female,23,Yes,4,3,2,1,5,6,7,No,Locking Period,Capital Appreciation,Wealth Creation,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants'], ['Male,30,Yes,3,6,4,2,5,1,7,Yes,Returns,Capital Appreciation,Wealth Creation,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television'], ['Male,22,Yes,2,1,3,7,6,4,5,Yes,Returns,Income,Wealth Creati

In [27]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

encoded = mlb.fit_transform(transactions)

print(encoded[:5])
print(len(mlb.classes_), "unique items")
print(mlb.classes_)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0]]
41 unique items
['Female,21,No,1,2,3,4,5,6,7,No,Returns,Capital Appreciation,Savings for Future,1-3 years,Weekly,20%-30%,Mutual Fund,Education,Dividend,Better Returns,Safe Investment,Risk Free,Internet'
 'Female,23,Yes,4,3,2,1,5,6,7,No,Locking Period,Capital Appreciation,Wealth Creation,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants'
 'Female,24,No,2,1,3,6,4,5,7,No,Returns,Income,Wealth Creation,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciatio

Handling Imbalanced Classes

In [31]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

iris = load_iris()

features = iris.data
target = iris. target

# remove first 40 observations
features = features [40:, : ]
target = target [40:]

# create binary target vector indicating if class 0
target = np.where((target == 0), 0, 1)
target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
# create weights
weights = {0: .9, 1: 0.1}

# Create random forest classifier with weights
RandomForestClassifier(class_weight=weights)

RandomForestClassifier(class_weight='balanced')

i_class0 = np.where(target == 0) [0]
i_class1 = np.where(target == 1) [0]

n_class0 = len(i_class0)
n_class1 = len(i_class1)

i_class1_downsampled = np.random.choice(i_class1, size=n_class0, replace=False)

np.hstack((target[i_class0], target[i_class1_downsampled]))



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
np.vstack((features[i_class0,:], features[i_class1_downsampled, : ] ) ) [0:5]

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4]])

In [35]:

i_class0_upsampled = np.random.choice(i_class0, size=n_class1, replace=True)

np.concatenate((target[i_class0_upsampled], target [i_class1] ) )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [36]:
np.vstack((features[i_class0_upsampled,:], features[i_class1,:]) ) [0:5]

array([[4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2]])