<a href="https://colab.research.google.com/github/JencyCS/DataScience/blob/main/Practical_3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sheth L.U.J and Sir M.V. college.**

# Jency Nadar T095
Finanace_data.csv

Rescaling a feature

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv("Finance_data.csv")

# Automatically detect numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numeric columns:", numeric_cols)

scaler = MinMaxScaler()

df_scaled = df.copy()
df_scaled[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print(df_scaled.head())


Numeric columns: Index(['age', 'Mutual_Funds', 'Equity_Market', 'Debentures',
       'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold'],
      dtype='object')
   gender       age Investment_Avenues  Mutual_Funds  Equity_Market  \
0  Female  0.928571                Yes      0.000000            0.2   
1  Female  0.142857                Yes      0.500000            0.4   
2    Male  0.642857                Yes      0.333333            1.0   
3    Male  0.071429                Yes      0.166667            0.0   
4  Female  0.214286                 No      0.166667            0.0   

   Debentures  Government_Bonds  Fixed_Deposits  PPF  Gold  ...  \
0    0.666667          0.333333        1.000000  1.0   0.4  ...   
1    0.166667          0.000000        0.666667  1.0   1.0  ...   
2    0.500000          0.166667        0.666667  0.0   1.0  ...   
3    0.333333          1.000000        0.833333  0.6   0.6  ...   
4    0.333333          0.833333        0.500000  0.8   1.0  ...   

         

Standardizing a Feature

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, RobustScaler

df = pd.read_csv("Finance_data.csv")

# detect numeric columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numeric columns:", num_cols)

# StandardScaler
std_scaler = StandardScaler()
df_standard_scaled = df.copy()
df_standard_scaled[num_cols] = std_scaler.fit_transform(df[num_cols])

# RobustScaler
rob_scaler = RobustScaler()
df_robust_scaled = df.copy()
df_robust_scaled[num_cols] = rob_scaler.fit_transform(df[num_cols])

print("\nStandard Scaled:")
print(df_standard_scaled.head())

print("\nRobust Scaled:")
print(df_robust_scaled.head())


Numeric columns: Index(['age', 'Mutual_Funds', 'Equity_Market', 'Debentures',
       'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold'],
      dtype='object')

Standard Scaled:
   gender       age Investment_Avenues  Mutual_Funds  Equity_Market  \
0  Female  1.763528                Yes     -1.311160      -1.319610   
1  Female -1.365312                Yes      1.226569      -0.424959   
2    Male  0.625768                Yes      0.380659       2.258993   
3    Male -1.649752                Yes     -0.465250      -2.214261   
4  Female -1.080872                 No     -0.465250      -2.214261   

   Debentures  Government_Bonds  Fixed_Deposits       PPF      Gold  ...  \
0   -0.453298         -1.220549        1.931494  2.501844 -1.749518  ...   
1   -2.266492         -2.700003        0.803614  2.501844  0.907978  ...   
2   -1.057696         -1.960276        0.803614 -0.645130  0.907978  ...   
3   -1.662094          1.738358        1.367554  1.243054 -0.863686  ...   
4   -1.662094 

Normalizing Observations


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Normalizer

df = pd.read_csv('Finance_data.csv')

feature_cols = ['Mutual_Funds', 'Equity_Market', 'Debentures',
                'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']
features = df[feature_cols].values

normalizer_l2 = Normalizer(norm="l2")
l2_normalized = normalizer_l2.transform(features)
l2_normalized_df = pd.DataFrame(l2_normalized, columns=[f'{col}_L2_Norm' for col in feature_cols])

print("--- L2 Normalized Features (First 5 rows) ---")
print(l2_normalized_df.head())

normalizer_l1 = Normalizer(norm="l1")
l1_normalized = normalizer_l1.transform(features)
l1_normalized_df = pd.DataFrame(l1_normalized, columns=[f'{col}_L1_Norm' for col in feature_cols])

print("\n--- L1 Normalized Features (First 5 rows) ---")
print(l1_normalized_df.head())

print("\nVerification (Sum of the first L1 Normalized row):", l1_normalized_df.iloc[0].sum())

# df_final = pd.concat([df, l2_normalized_df, l1_normalized_df], axis=1)

--- L2 Normalized Features (First 5 rows) ---
   Mutual_Funds_L2_Norm  Equity_Market_L2_Norm  Debentures_L2_Norm  \
0              0.084515               0.169031            0.422577   
1              0.338062               0.253546            0.169031   
2              0.253546               0.507093            0.338062   
3              0.169031               0.084515            0.253546   
4              0.169031               0.084515            0.253546   

   Government_Bonds_L2_Norm  Fixed_Deposits_L2_Norm  PPF_L2_Norm  Gold_L2_Norm  
0                  0.253546                0.591608     0.507093      0.338062  
1                  0.084515                0.422577     0.507093      0.591608  
2                  0.169031                0.422577     0.084515      0.591608  
3                  0.591608                0.507093     0.338062      0.422577  
4                  0.507093                0.338062     0.422577      0.591608  

--- L1 Normalized Features (First 5 rows) ---


Grouping Observations Using Clustering

In [3]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('Finance_data.csv')

clustering_features = [
    'Mutual_Funds', 'Equity_Market', 'Debentures', 'Government_Bonds',
    'Fixed_Deposits', 'PPF', 'Gold', 'age'
]

features = df[clustering_features].copy()

features.fillna(features.mean(), inplace=True)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

scaled_df = pd.DataFrame(scaled_features, columns=clustering_features)

clusterer = KMeans(n_clusters=3, random_state=0, n_init='auto')

clusterer.fit(scaled_df)

df['Cluster_Group'] = clusterer.predict(scaled_df)

print("--- Data after K-Means Clustering (First 5 Rows) ---")
print(df[['age', 'Avenue', 'Expect', 'Cluster_Group']].head())

print("\n--- Cluster Sizes ---")
print(df['Cluster_Group'].value_counts().sort_index())

cluster_avenue_preference = df.groupby('Cluster_Group')['Avenue'].value_counts(normalize=True).mul(100).rename('Percentage').reset_index()
print("\n--- Investment Avenue Preference by Cluster ---")
print(cluster_avenue_preference)

--- Data after K-Means Clustering (First 5 Rows) ---
   age       Avenue   Expect  Cluster_Group
0   34  Mutual Fund  20%-30%              1
1   23  Mutual Fund  20%-30%              2
2   30       Equity  20%-30%              2
3   22       Equity  10%-20%              0
4   24       Equity  20%-30%              0

--- Cluster Sizes ---
Cluster_Group
0    14
1    21
2     5
Name: count, dtype: int64

--- Investment Avenue Preference by Cluster ---
   Cluster_Group                 Avenue  Percentage
0              0                 Equity   35.714286
1              0         Fixed Deposits   28.571429
2              0            Mutual Fund   28.571429
3              0  Public Provident Fund    7.142857
4              1            Mutual Fund   52.380952
5              1         Fixed Deposits   23.809524
6              1                 Equity   14.285714
7              1  Public Provident Fund    9.523810
8              2            Mutual Fund   60.000000
9              2           

Deleteing Observations with Missing Values

In [8]:
import numpy as np
import pandas as pd

df = pd.read_csv("Finance_data.csv")
features = df.select_dtypes(include=['int64', 'float64']).values
clean_features = features[~np.isnan(features).any(axis=1)]
print(clean_features[:10])


[[34  1  2  5  3  7  6  4]
 [23  4  3  2  1  5  6  7]
 [30  3  6  4  2  5  1  7]
 [22  2  1  3  7  6  4  5]
 [24  2  1  3  6  4  5  7]
 [24  7  5  4  6  3  1  2]
 [27  3  6  4  2  5  1  7]
 [21  2  3  7  4  6  1  5]
 [35  2  4  7  5  3  1  6]
 [31  1  3  7  4  5  2  6]]


Deleteing Observations with Missing Values

In [9]:
import pandas as pd
from sklearn.impute import SimpleImputer

df = pd.read_csv("Finance_data.csv")
numeric_df = df.select_dtypes(include=['int64', 'float64'])

mean_imputer = SimpleImputer(strategy="mean")
imputed_data = mean_imputer.fit_transform(numeric_df)

imputed_df = pd.DataFrame(imputed_data, columns=numeric_df.columns)
print(imputed_df.head(10))


    age  Mutual_Funds  Equity_Market  Debentures  Government_Bonds  \
0  34.0           1.0            2.0         5.0               3.0   
1  23.0           4.0            3.0         2.0               1.0   
2  30.0           3.0            6.0         4.0               2.0   
3  22.0           2.0            1.0         3.0               7.0   
4  24.0           2.0            1.0         3.0               6.0   
5  24.0           7.0            5.0         4.0               6.0   
6  27.0           3.0            6.0         4.0               2.0   
7  21.0           2.0            3.0         7.0               4.0   
8  35.0           2.0            4.0         7.0               5.0   
9  31.0           1.0            3.0         7.0               4.0   

   Fixed_Deposits  PPF  Gold  
0             7.0  6.0   4.0  
1             5.0  6.0   7.0  
2             5.0  1.0   7.0  
3             6.0  4.0   5.0  
4             4.0  5.0   7.0  
5             3.0  1.0   2.0  
6           

Imputing Missing Values

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

df = pd.read_csv("Finance_data.csv")
features = df.select_dtypes(include=['int64', 'float64']).values

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

mean_imputer = SimpleImputer(strategy="mean")
features_mean_imputed = mean_imputer.fit_transform(standardized_features)

print(true_value)
print(features_mean_imputed[0, 0])


1.7635283843645801
-0.045218676522168925
